### ISSUE TITLE
[FR] Dimmer pop-up

### ISSUE THREAD

**Issue by donhimol** [jimz011/homekit-infused#17]
Dedicated popup for dimmers with supported_features=1.

**Comment by MagicMountainMan** [comment]
I would propose another group category for dimmers specifically as I have this same issue.

For example, in the rooms_and_groups.yaml it would look like this:
`# Room 1
  room_1_dimmers:
    entities: # light.bedroom_dimmer
  room_1_lights_default:
    entities: # light.plafond, light.eettafel
  room_1_lights_rgb:
    entities: # light.woonkamer_led_lampen, light.gateway_light_7811dcdef324
  room_1_lights_color_temp:
    entities: # light.vloerlamp, light.tafellamp
  room_1_all_devices:
    entities:
     # - light.plafond
     # - light.eettafel
     # - light.vloerlamp`

And in the auto_fill_light_template.yaml it would add another include group:
` - group: {{ group_dimmer|default('group.empty_group') }}
     options:
       !include
       - button.yaml
       - entity: this.entity_id
          label: '!include ../includes/brightness-label.yaml'
          grid:
            '!include ../includes/light-devices-grid.yaml'
          template: dimmer_popup.yaml
          lock: {{ lock|default('false') }}`

Which would necessitate the creation of a new template, dimmer_popup.yaml, which would look like this: 

(Note that the only difference between dimmer_popup.yaml and switch_popup.yaml is the subtraction of the global variable for the supportedFeaturesTreshold and it instead being -1 which forces a dimmer popup)

`# lovelace_gen

# card
type: custom:light-popup-card
entity: {{ entity }}
brightnessWidth: 110px
brightnessHeight: 410px
switchWidth: 110px
switchHeight: 410px
fullscreen: false
supportedFeaturesTreshold: -1
settings: true`

And in the 03.lights.yaml view would require a simple "group_dimmer: group.room_1_dimmers" line.

Perhaps this addition could just be commented out in the introduction of the rooms_and_groups file so that only people who are having this issue really need to implement this? Otherwise, Lovelace Gen will just ignore the fact that for the most part "group_dimmer" is never populated and most people won't know the difference.

**Comment by jimz011** [comment]
I will look into this, however I might revise the groups within the upcoming week. So I keep it on hold for a while.

**Comment by MagicMountainMan** [comment]
This looks to have been fixed somewhere down the line, I added -1 to the supportedFeaturesThreshold and it didn't break my non dimming switches.

**Comment by jimz011** [comment]
@donhimol could you please check it if this is the case for you as well? If yes I will close this issue.

**Comment by jimz011** [comment]
Is this still an issue?

**Comment by jimz011** [comment]
After reading the documentation of this card I found that the supportedFeaturesTreshold has been removed entirely and replaced by an option to force the card into a slider. If you still use HKI and you still face this problem with the new card please let me know and I will add an option to force it. For now I will close this issue!

**Comment by jimz011** [comment]
I know I have closed this issue, but it wasn't really resolved so I heard.

I have fixed this issue in HKI 3.0.5 where you can force a switch or a slider depending on your needs. Note that this will only work when adding the buttons separately and it won't work with the auto fill addons. Please read the new documentation of the single buttons on how to do this.

You must have HKI 3.0.5 for this to work, which will be released in a few hours!
